### ISSUE TITLE
Right to Ask Logo in GitHub Org

### ISSUE THREAD

**Issue by KipCrossing** [RightToAskOrg/righttoask-docs#1]
Hi @vteague,

Can you please add the RTA logo image to the GitHub org?

![Screenshot from 2021-03-22 19-58-00](https://user-images.githubusercontent.com/7298449/111964722-06546600-8b49-11eb-881d-26115d22a96d.png)

**Comment by vteague** [comment]
Done! Thanks @KipCrossing

**Comment by KipCrossing** [comment]
Awesome!
